# Generated by Django 2.1a1 on 2018-06-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('vm_name', models.CharField(max_length=100)),
                ('vm_ip', models.CharField(max_length=50)),
                ('vm_status', models.CharField(max_length=20)),
            ],
        ),
    ]
