# Generated by Django 2.1a1 on 2018-06-15 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0002_auto_20180611_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='vm_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=10, verbose_name='主机')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('ios_ver', models.CharField(blank=True, max_length=100, verbose_name='系统版本')),
                ('package', models.CharField(blank=True, max_length=100, verbose_name='镜像版本')),
                ('user', models.CharField(blank=True, max_length=20, verbose_name='使用人')),
                ('purposes', models.CharField(max_length=100, verbose_name='用途')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ip', models.GenericIPAddressField(protocol='ipv4', unique=True, verbose_name='IP')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
            ],
        ),
        migrations.DeleteModel(
            name='VMDetails',
        ),
    ]
