# Generated by Django 2.1a1 on 2018-06-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0005_auto_20180619_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_info',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
