# Generated by Django 2.1a1 on 2018-06-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0009_auto_20180620_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_info',
            name='status',
            field=models.CharField(blank=True, max_length=10, verbose_name='状态'),
        ),
    ]
