# Generated by Django 2.1a1 on 2018-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0010_auto_20180620_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_info',
            name='user',
            field=models.CharField(blank=True, max_length=20, verbose_name='申请人'),
        ),
    ]
