# Generated by Django 2.1a1 on 2018-06-25 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0011_auto_20180622_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('created_by', models.CharField(max_length=20, verbose_name='创建人')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('ip', models.GenericIPAddressField(protocol='ipv4', verbose_name='访问IP')),
            ],
        ),
        migrations.RenameModel(
            old_name='vm_info',
            new_name='VmInfo',
        ),
    ]
