# Generated by Django 2.1a1 on 2018-07-10 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0012_auto_20180625_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmHardware',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('vm_id', models.IntegerField()),
                ('host', models.CharField(max_length=10)),
                ('xml', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('memory', models.IntegerField()),
                ('vcpu', models.IntegerField()),
                ('storage', models.CharField(max_length=500)),
                ('network', models.CharField(max_length=500)),
                ('modified_time', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
