# Generated by Django 2.1a1 on 2018-07-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0014_auto_20180711_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmhardware',
            name='vm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
