# Generated by Django 2.1a1 on 2018-07-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0015_auto_20180711_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmhardware',
            name='network',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='vmhardware',
            name='storage',
            field=models.CharField(max_length=3000),
        ),
    ]
