# Generated by Django 2.1a1 on 2018-07-30 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0016_auto_20180711_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vminfo',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
    ]
